version: "3.9"

services:
  minio:
    container_name: minio
    image: bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: pastebin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  pastebin:
    container_name: pastebin
    image: pastebin:latest
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio

