
CREATE TABLE IF NOT EXISTS paste
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(100)                            NOT NULL,
    minio_url VARCHAR                                 NOT NULL,
    CONSTRAINT pk_paste PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS record
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url VARCHAR                                 NOT NULL,
    paste_id BIGINT,
    CONSTRAINT pk_record PRIMARY KEY (id)
);

ALTER TABLE record
    ADD CONSTRAINT FK_RECORD_ON_PASTE FOREIGN KEY (paste_id) REFERENCES paste (id);