create table if not exists paste
{
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(100)                            NOT NULL,
    minio_url    VARCHAR(100)                            NOT NULL
};

create table if not exists record
{
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url          VARCHAR(8)                              NOT NULL,
};